I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script call
    call first_meet
  File "game/meet.rpy", line 27, in script
    center "{cps=20}Suzuki and Teddy, while infiltrating the dinosaur kingdom, stumble upon a clandestine council of dinosaurs advocating for peace. The player decides how Suzuki reacts to this revelation.{/cps}{w=0.5}{nw}"
Exception: Parameter 'interact' is not known by ATL Transform.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script call
    call first_meet
  File "game/meet.rpy", line 27, in script
    center "{cps=20}Suzuki and Teddy, while infiltrating the dinosaur kingdom, stumble upon a clandestine council of dinosaurs advocating for peace. The player decides how Suzuki reacts to this revelation.{/cps}{w=0.5}{nw}"
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\exports.py", line 1493, in say
    who(what, *args, **kwargs)
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\atl.py", line 617, in __call__
    raise Exception('Parameter %r is not known by ATL Transform.' % k)
Exception: Parameter 'interact' is not known by ATL Transform.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
Capybaras vs Dinosaurs 1.0
Tue Feb 20 11:45:03 2024
