I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script call
    call home
  File "game/lake.rpy", line 81, in script call
    call call_or_steps
  File "game/lake.rpy", line 103, in script call
    call zvanok
  File "game/agency.rpy", line 26, in script
    agenct "You have no other option"
Exception: Sayer 'agenct' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script call
    call home
  File "game/lake.rpy", line 81, in script call
    call call_or_steps
  File "game/lake.rpy", line 103, in script call
    call zvanok
  File "game/agency.rpy", line 26, in script
    agenct "You have no other option"
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'agenct' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
Capybaras vs Dinosaurs 1.0
Fri Feb 23 00:34:53 2024
