I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script call
    call main_menu
  File "game/script.rpy", line 15, in script call
    call main_menu
ScriptError: could not find label 'main_menu'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script call
    call main_menu
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 1416, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 15, in script call
    call main_menu
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'main_menu'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
Capybaras vs Dinosaurs 
Tue Feb 27 18:05:28 2024
